import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { CardActionArea, CardActions, CardMedia, Container, Typography } from '@mui/material'
import styles from '../styles/header.module.css'
import Header from '../components/header';
import { Button } from '@mui/material'
import { Grid } from '@mui/material'
import { Card } from '@mui/material'
import CardContent from '@mui/material/CardContent'
import scarfLady from '../public/scarflady.png';
import { Box } from '@mui/system'
import ScarfImage from '../components/homepageimg';
import ExtraSpace from '../components/extraspace';
import Extraspace from '../components/extraspace'
import Data from '../utils/data';

const Home: NextPage = () => {
  return (
    <div>
      <Header/>
      <div className={styles.imagebackground} >
        <h1 className={styles.imgtext}>want to show off your cursed knitted scarves? </h1>
        <Extraspace/>
      </div> 
      <div>
          <h1 className={styles.producttxt}>products</h1>
          <Grid container spacing={3}>
            {Data.products.map((product) => (
              <Grid item md={4} key={product.name}>
                <Card>
                  <CardActionArea>
                    <CardMedia component="img" image={product.image} 
                      title={product.name}></CardMedia>
                      <CardContent>
                        <Typography>
                          {product.name}
                        </Typography>
                        <Typography>
                          {product.description}
                        </Typography>
                      </CardContent>
                  </CardActionArea>
                  <CardActions>
                    <Button size="small">Add to cart</Button>
                  </CardActions>
                </Card>
              </Grid>
            ))}
          </Grid>
        </div>
    </div>
 
    
    
  
    
    
    /*<div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div> */
  )
}

export default Home
